### ISSUE TITLE
Proton websites blocked

### ISSUE THREAD

**Issue by Pazzou** [az0/vpn_ip#2]
Hello,

First, I would like to thank you for the job of maintaining daily this database of hostnames and IP addresses that is really helpful !

I saw that the proton cloud domains are all bannished instead of juste the protonvpn domains.
I saw those domains that may not be exhaustives :

drive.proton.me
mail.proton.me
mail-api.proton.me
pass.proton.me
pass-api.proton.me
reports.proton.me
vip-fr3-storage.proton.me
zrh-storage.proton.me

Should they be whitelisted or not ? If not, why ?

**Comment by az0** [comment]
Good point. I will remove domains not associated with VPN services.  A few look like mail and file storage. Do you know more about reports.proton.me ?

**Comment by Pazzou** [comment]
Well not really, the domain isn't up actually. Advices are differents, some says it's a VPN IP (IPWHOIS), some says a data center (AbuseIPDB), others says it's a mail (VT)...
This one might be keep in the blacklist you're right.

<img width="435" alt="Screenshot 2024-11-18 at 17 26 38" src="https://github.com/user-attachments/assets/4361c80e-5893-47f7-9663-91b5c070fa96">
<img width="431" alt="Screenshot 2024-11-18 at 17 26 48" src="https://github.com/user-attachments/assets/2027cf23-523e-485e-bb06-85cc9f839fc9">
<img width="379" alt="Screenshot 2024-11-18 at 17 26 57" src="https://github.com/user-attachments/assets/782c9dcd-3b4f-4f15-a9c3-9a174b2cc3bb">
<img width="467" alt="Screenshot 2024-11-18 at 17 28 30" src="https://github.com/user-attachments/assets/ccd8e414-269e-4f16-beb9-9f8cd58ab33a">

**Comment by az0** [comment]
I moved 24 proton.me hostnames to the allowlist

**Comment by Pazzou** [comment]
Did you removed those I told you except for reports.proton.me ?
Because when I search here https://raw.githubusercontent.com/az0/vpn_ip/refs/heads/main/data/output/hostname.txt I still find the others proton services...

**Comment by az0** [comment]
Try again. You may have checked before the automated update finished
updating the final outputs.
